name: Pull Request Action
on:
  push:
    branches:
      - newbranch
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
jobs:
  create-pull-request:
    permissions: read-all|write-all
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          pr_label: "This PR is automated"
          pr_title: " Simple automated PR"
